#scoop uninstall balabolka
#scoop uninstall bittorrent
#scoop uninstall citra
#scoop uninstall equalizerapo
scoop uninstall flstudio
#scoop uninstall geforce
#scoop uninstall gog2
scoop uninstall logos
#scoop uninstall midiox
#scoop uninstall nordvpn
scoop uninstall office07
#scoop uninstall pc_equalizer_gui
#scoop uninstall pdfcandy
scoop uninstall razersynapse2
#scoop uninstall scite4ahk
#scoop uninstall visualboyadvance